
import React, { useEffect, useRef, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Result.module.css'
import { Skeleton } from "baseui/skeleton";
import { ThemeProvider, LightTheme, DarkTheme } from 'baseui';
import { useStyletron } from 'baseui';
import { useRouter } from 'next/router';
import { Display4 } from 'baseui/typography';




const THEME = {
    light: 'light',
    dark: 'dark',
};



export default function Home({ props }) {
    const [theme, setTheme] = React.useState(THEME.dark);
    const [css] = useStyletron()
    return (
        <div
            className={css({
                display: "flex",
                flexDirection: "column",
                // justifyContent:"space-between",
                minHeight: "100vh",
                paddingLeft: "5%",
            })}>


            <Head>
                <title>Declined Location</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <ThemeProvider theme={theme === THEME.light ? LightTheme : DarkTheme}>

                <Display4>
                    Thanks for visiting us <br />
                    Since you declined to allow location accesse we are not able to help you <br />
                    right now. <br />
                    But feel free to change your setting and come back to us.
                </Display4>

            </ThemeProvider >


        </div >
    )
}


