
import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Skeleton } from "baseui/skeleton";
import { ThemeProvider, LightTheme, DarkTheme } from 'baseui';
import { Button, SIZE } from 'baseui/button';

import {

  H1,

} from 'baseui/typography';

const THEME = {
  light: 'light',
  dark: 'dark',
};

export default function Home() {
  const [theme, setTheme] = React.useState(THEME.dark);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={theme === THEME.light ? LightTheme : DarkTheme}>
        <main>
          <section>

            <H1 $style={{
              fontSize: '76px',
              fontWeight: '600',
              lineHeight: '88px'
            }}>
              Your   <br />
              Current   <br />
              Location   <br />
            </H1>

            <Button
              size={SIZE.large}>
              Get Location
            </Button>

          </section>



        </main>
      </ThemeProvider>


    </div>
  )
}
